plugins {
    id 'groovy-gradle-plugin'
    id 'maven-publish'
}

group = 'net.trackme.conventions'

def rootProps = new Properties()
new File(rootDir.parentFile, 'gradle.properties').withInputStream { rootProps.load(it) }
version = providers.gradleProperty('version').getOrElse(rootProps.getProperty('version'))

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation 'net.ltgt.gradle:gradle-errorprone-plugin:5.1.0'
}

publishing {
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/Students-buisness-incubator-of-TUSUR/track-me-platform')
            credentials {
                username = project.findProperty('gpr.user') ?: System.getenv('GITHUB_ACTOR')
                password = project.findProperty('gpr.key') ?: System.getenv('GITHUB_TOKEN')
            }
        }
    }
}
